name: MyMemorian
main: org.drtoasti.mymemorian.MyMemorian
version: 1.0
author: DrToasti
description: TestPlugin


commands:
  heal:
    description: healing a player
    usage: /<command> <life|food> <player|all>
    permission: mymemorian.heal
    permission-message: 'Dazu fehlt dir die Berechtigung!'
    
  gladi:
    description: spamt gladi zu
    usage: /<command>
    permission: mymemorian.gladi
    permission-message: 'Dazu fehlt dir die Berechtigung!'
    
  teamchat:
    description: bla
    usage: /<command> <nachricht>
    permission: mymemorian.teamchat
    permission-message: 'Dazu fehlt dir die Berechtigung!'
    aliases: tc
    
  join:
    description: bla
    usage: /<command> <team>
    permission: mymemorian.join
  kill:
    description: kill a player
    usage: /<command>
    permission: mymemorian.kill
    permission-message: 'Dazu fehlt dir die Berechtigung!'
  give:
    description: give a item a player
    usage: /<command>
    permission: mymemorian.give
    permission-message: 'Dazu fehlt dir die Berechtigung!'
  msg:
    description: give a item a player
    usage: /<command>
    permission: mymemorian.give
    permission-message: 'Dazu fehlt dir die Berechtigung!'
  broadcast:
    description: send a broadcast message
    usage: /<command> <text>
    permission: mymemorian.broadcast
    permission-message: 'Dazu fehlt dir die Berechtigung!'