name: MyMemorian
main: org.drtoasti.mymemorian.MyMemorian
version: 1.0
author: DrToasti
description: Plugin with useful commands


commands:
  heal:
    description: healing a player
    usage: /<command> <life|food> <player|all>
    permission: mymemorian.heal
    permission-message: 'Dazu fehlt dir die Berechtigung!'
    
  gladi:
    description: spamt gladi zu
    usage: /<command>
    permission: mymemorian.gladi
    permission-message: 'Dazu fehlt dir die Berechtigung!'
    
  teamchat:
    description: bla
    usage: /<command> <nachricht>
    permission: mymemorian.teamchat
    permission-message: 'Dazu fehlt dir die Berechtigung!'
    aliases: tc
    
  join:
    description: bla
    usage: /<command> <team>
    permission: mymemorian.join
  kill:
    description: kill a player
    usage: /<command>
    permission: mymemorian.kill
    permission-message: 'Dazu fehlt dir die Berechtigung!'
  give:
    description: give a item a player
    usage: /<command>
    permission: mymemorian.give
    permission-message: 'Dazu fehlt dir die Berechtigung!'
  msg:
    description: give a item a player
    usage: /<command>
    permission: mymemorian.give
    permission-message: 'Dazu fehlt dir die Berechtigung!'
  broadcast:
    description: send a broadcast message
    usage: /<command> <text>
    permission: mymemorian.broadcast
    permission-message: 'Dazu fehlt dir die Berechtigung!'
    aliases: bc
  exp:
    description: give a player exp
    usage: /<command> <exp> [Player]
    permission: mymemorian.exp
    permission-message: 'Dazu fehlt dir die Berechtigung!'
  fly:
    description: give a player fly
    usage: /<command> [Player]
    permission: mymemorian.fly
    permission-message: 'Dazu fehlt dir die Berechtigung!'
  gamemode:
    description: change the gamemode
    usage: /<command> <mode> [Player]
    permission: mymemorian.gamemode
    permission-message: 'Dazu fehlt dir die Berechtigung!'
    aliases: gm
  op:
    description: give a player OP
    usage: /<command> [Player]
    permission: mymemorian.op
    permission-message: 'Dazu fehlt dir die Berechtigung!'
  deop:
    description: deop a OP player
    usage: /<command> [Player]
    permission: mymemorian.deop
    permission-message: 'Dazu fehlt dir die Berechtigung!'
  sethead:
    description: place a Block on the head
    usage: /<command>
    permission: mymemorian.sethead
    permission-message: 'Dazu fehlt dir die Berechtigung!'
  clearinventory:
    description: clear the inventory
    usage: /<command>
    permission: mymemorian.clearinventory
    permission-message: 'Dazu fehlt dir die Berechtigung!'
    aliases: ci